name: A workflow for my Hello World file
on:
  push:
    braches: [ main ]
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./action-linter
        with:
          MY_NAME: "swyo"

